language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

sudo: false

env:
  global:
    - DEFAULT=1

services:
  - docker

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true

  include:
  - php: 7.1
    env: PHPCS=1 DEFAULT=0

before_install:
  - if [ $DEFAULT = '1' ]; then sh ./ci/launch_selenium.sh; fi

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

before_script:
  - if [ $DEFAULT = '1' ]; then vendor/bin/codecept build; fi
  - if [ $PHPCS = '1' ]; then composer require squizlabs/php_codesniffer; fi

script:
  - if [ $DEFAULT = '1' ]; then vendor/bin/codecept run; fi
  - if [ $PHPCS = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=PSR2 ./src; fi

notifications:
  email: false
